# Generated by Django 5.0.4 on 2024-04-30 12:57

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behaviours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviorindicator',
            name='lft',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='behaviorindicator',
            name='rght',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='behaviorindicator',
            name='tree_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='behaviorindicator',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='behaviours.behaviorindicator'),
        ),
    ]
