# Generated by Django 5.0.4 on 2024-05-12 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behaviours', '0003_alter_behaviorindicator_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behaviorrecord',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='behaviours.behaviorindicator', verbose_name='Performance Indicator'),
        ),
    ]
